### ISSUE TITLE
[Utils] [ERROR] [Error] org.testng.TestNGException:  Parameter &apos;Browser&apos; is required by @Test on method startBrowser but has not been marked @Optional or defined in

### ISSUE THREAD

**Issue by prashanth624** [browserstack/testng-browserstack#30]
Hi All

I am seeing below error when I run a program in Jenkins using Github repository. Program executed fine with Maven and in local

[INFO] Running TestSuite
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Parameter &apos;Browser&apos; is required by @Test on method startBrowser but has not been marked @Optional or defined
in C:\Windows\System32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\Selenium Maven Github\testng.xml
	at org.testng.internal.Parameters.createParams(Parameters.java:268)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:356)
	at org.testng.internal.Parameters.createParameters(Parameters.java:700)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:875)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.126 s <<< FAILURE! - in TestSuite
[ERROR] mavenforjenkins.UITest.startBrowser  Time elapsed: 1.923 s  <<< FAILURE!
org.testng.TestNGException:

**Comment by harsh-browserstack** [comment]
Hi,

The above error that you are getting is not related to Browserstack specifically and is a configuration issue at your end.

Can you let me know whether you have passed 'browser' capability in your test to run on? In case not then kindly add the capability and run your tests.

You can refer to the following link for the capability generator:
https://www.browserstack.com/automate/capabilities
